spring.application.name=Backend

server.port=9090

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bluemoon
spring.datasource.username=root
spring.datasource.password=123123hung
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=admin.bluemoon.project@gmail.com
spring.mail.password=zvevyejsemryyslt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA/Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Thymeleaf Configuration
spring.thymeleaf.check-template-location=false

#Ném lỗi khi gặp thuộc tính lạ
spring.jackson.deserialization.fail-on-unknown-properties=true
# Chuỗi khóa bí mật (Secret Key) phải đủ dài (ít nhất 256-bit) và được mã hóa Base64
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của Token tính bằng mili-giây (Ví dụ: 86400000 = 24 giờ)
app.jwt.expiration-milliseconds=86400000

# --- VNPAY CONFIGURATION ---
vnpay.tmn-code=B9QSNH8Q
vnpay.hash-secret=7YUOOOJOKIPUU1PSW1I7SDSPP1MNTZA3
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:9090/api/payments/vnpay/return
vnpay.frontend-return-url=http://localhost:5173/payment-result