spring.application.name=Backend

server.port=9090

# MySQL Configuration
spring.datasource.url=jdbc:mysql://bluemoon-bluemoon-n7.c.aivencloud.com:22416/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_vIw_fKzLRoTKWqBJwTN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.forward-headers-strategy=framework

# Spring mail configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=05a6a965615cc2
spring.mail.password=e4b54278489a41
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA/Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#Thymeleaf Configuration
spring.thymeleaf.check-template-location=false

#Ném lỗi khi gặp thuộc tính lạ
spring.jackson.deserialization.fail-on-unknown-properties=true
# Chuỗi khóa bí mật (Secret Key) phải đủ dài (ít nhất 256-bit) và được mã hóa Base64
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Thời gian sống của Token tính bằng mili-giây (Ví dụ: 86400000 = 24 giờ)
app.jwt.expiration-milliseconds=86400000

# --- VNPAY CONFIGURATION ---
vnpay.tmn-code=7WR4PJWS
vnpay.hash-secret=5WEAR2LP8GHIZTZKQ0JKBX66GN84NRF3
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#vnpay.return-url=http://localhost:9090/api/payments/vnpay/return
vnpay.return-url=https://certainly-unpledged-prune.ngrok-free.dev/api/payments/vnpay/return
vnpay.frontend-return-url=http://localhost:5173/payment-result